import {
  Server,
  Database,
  Cloud,
  Globe,
  Monitor,
  Laptop,
  Smartphone,
  Tablet,
  User,
  Users,
  Shield,
  KeyRound,
  Lock,
  GitBranch,
  GitMerge,
  Container,
  Box,
  Boxes,
  Layers,
  Cpu,
  HardDrive,
  MemoryStick,
  CircuitBoard,
  Network,
  Wifi,
  Router,
  Waypoints,
  Route,
  Mail,
  MessageSquare,
  Send,
  Bell,
  FileText,
  Folder,
  Search,
  Activity,
  Gauge,
  Clock,
  Calendar,
  Zap,
  Workflow,
  Plug,
  Code,
  Terminal,
  Bot,
  Brain,
  Sparkles,
  CreditCard,
  ShoppingCart,
  Truck,
  Building2,
  Rocket,
  Flame,
  Package,
  CloudCog,
  ServerCog,
  Camera,
  Printer,
  QrCode,
  type LucideIcon,
} from "lucide-react";

/** Curated icon set available to diagram nodes. */
export const ICON_MAP: Record<string, LucideIcon> = {
  Server,
  Database,
  Cloud,
  Globe,
  Monitor,
  Laptop,
  Smartphone,
  Tablet,
  User,
  Users,
  Shield,
  KeyRound,
  Lock,
  GitBranch,
  GitMerge,
  Container,
  Box,
  Boxes,
  Layers,
  Cpu,
  HardDrive,
  MemoryStick,
  CircuitBoard,
  Network,
  Wifi,
  Router,
  Waypoints,
  Route,
  Mail,
  MessageSquare,
  Send,
  Bell,
  FileText,
  Folder,
  Search,
  Activity,
  Gauge,
  Clock,
  Calendar,
  Zap,
  Workflow,
  Plug,
  Code,
  Terminal,
  Bot,
  Brain,
  Sparkles,
  CreditCard,
  ShoppingCart,
  Truck,
  Building2,
  Rocket,
  Flame,
  Package,
  CloudCog,
  ServerCog,
  Camera,
  Printer,
  QrCode,
};

export const ICON_KEYS = Object.keys(ICON_MAP);

export interface Tone {
  fill: string;
  stroke: string;
  textColor: string;
}

export const TONES: Record<string, Tone> = {
  blue: { fill: "#e0f2fe", stroke: "#0284c7", textColor: "#075985" },
  green: { fill: "#dcfce7", stroke: "#16a34a", textColor: "#166534" },
  amber: { fill: "#fef3c7", stroke: "#d97706", textColor: "#92400e" },
  red: { fill: "#fee2e2", stroke: "#dc2626", textColor: "#991b1b" },
  pink: { fill: "#fce7f3", stroke: "#db2777", textColor: "#9d174d" },
  indigo: { fill: "#e0e7ff", stroke: "#4f46e5", textColor: "#3730a3" },
  teal: { fill: "#ccfbf1", stroke: "#0d9488", textColor: "#115e59" },
  purple: { fill: "#ede9fe", stroke: "#7c3aed", textColor: "#5b21b6" },
  slate: { fill: "#f1f5f9", stroke: "#475569", textColor: "#334155" },
  orange: { fill: "#ffedd5", stroke: "#ea580c", textColor: "#9a3412" },
};

export interface IconPreset {
  icon: string;
  labelKey: string;
  tone: keyof typeof TONES;
}

/** Icon components shown in the shape palette. */
export const ICON_PRESETS: IconPreset[] = [
  { icon: "Server", labelKey: "icon.server", tone: "blue" },
  { icon: "CloudCog", labelKey: "icon.cloudService", tone: "blue" },
  { icon: "Database", labelKey: "icon.database", tone: "amber" },
  { icon: "HardDrive", labelKey: "icon.disk", tone: "slate" },
  { icon: "MemoryStick", labelKey: "icon.memory", tone: "slate" },
  { icon: "Layers", labelKey: "icon.cache", tone: "red" },
  { icon: "Container", labelKey: "icon.container", tone: "blue" },
  { icon: "Box", labelKey: "icon.service", tone: "green" },
  { icon: "Boxes", labelKey: "icon.cluster", tone: "green" },
  { icon: "Cpu", labelKey: "icon.compute", tone: "indigo" },
  { icon: "CircuitBoard", labelKey: "icon.hardware", tone: "indigo" },
  { icon: "Network", labelKey: "icon.network", tone: "blue" },
  { icon: "Router", labelKey: "icon.router", tone: "blue" },
  { icon: "Waypoints", labelKey: "icon.gateway", tone: "purple" },
  { icon: "Route", labelKey: "icon.route", tone: "purple" },
  { icon: "Wifi", labelKey: "icon.wireless", tone: "blue" },
  { icon: "Globe", labelKey: "icon.internet", tone: "indigo" },
  { icon: "Monitor", labelKey: "icon.desktop", tone: "slate" },
  { icon: "Laptop", labelKey: "icon.laptop", tone: "slate" },
  { icon: "Smartphone", labelKey: "icon.mobile", tone: "slate" },
  { icon: "Tablet", labelKey: "icon.tablet", tone: "slate" },
  { icon: "User", labelKey: "icon.user", tone: "teal" },
  { icon: "Users", labelKey: "icon.users", tone: "teal" },
  { icon: "Shield", labelKey: "icon.security", tone: "green" },
  { icon: "KeyRound", labelKey: "icon.auth", tone: "amber" },
  { icon: "Lock", labelKey: "icon.encryption", tone: "red" },
  { icon: "GitBranch", labelKey: "icon.vcs", tone: "orange" },
  { icon: "GitMerge", labelKey: "icon.merge", tone: "orange" },
  { icon: "MessageSquare", labelKey: "icon.message", tone: "pink" },
  { icon: "Send", labelKey: "icon.stream", tone: "pink" },
  { icon: "Mail", labelKey: "icon.mail", tone: "pink" },
  { icon: "Bell", labelKey: "icon.notify", tone: "amber" },
  { icon: "FileText", labelKey: "icon.log", tone: "slate" },
  { icon: "Folder", labelKey: "icon.storage", tone: "amber" },
  { icon: "Search", labelKey: "icon.search", tone: "blue" },
  { icon: "Activity", labelKey: "icon.monitor", tone: "red" },
  { icon: "Gauge", labelKey: "icon.metrics", tone: "red" },
  { icon: "Clock", labelKey: "icon.cron", tone: "slate" },
  { icon: "Zap", labelKey: "icon.event", tone: "orange" },
  { icon: "Workflow", labelKey: "icon.workflow", tone: "purple" },
  { icon: "Plug", labelKey: "icon.plugin", tone: "orange" },
  { icon: "Code", labelKey: "icon.code", tone: "slate" },
  { icon: "Terminal", labelKey: "icon.cli", tone: "slate" },
  { icon: "Bot", labelKey: "icon.agent", tone: "purple" },
  { icon: "Brain", labelKey: "icon.model", tone: "purple" },
  { icon: "Sparkles", labelKey: "icon.ai", tone: "pink" },
  { icon: "CreditCard", labelKey: "icon.payment", tone: "green" },
  { icon: "ShoppingCart", labelKey: "icon.ecommerce", tone: "orange" },
  { icon: "Truck", labelKey: "icon.logistics", tone: "blue" },
  { icon: "Building2", labelKey: "icon.enterprise", tone: "slate" },
  { icon: "Rocket", labelKey: "icon.deploy", tone: "red" },
  { icon: "Flame", labelKey: "icon.hot", tone: "red" },
  { icon: "Package", labelKey: "icon.artifact", tone: "amber" },
  { icon: "Camera", labelKey: "icon.media", tone: "purple" },
  { icon: "Printer", labelKey: "icon.print", tone: "slate" },
  { icon: "QrCode", labelKey: "icon.qrcode", tone: "slate" },
];
